# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19b937a93acad167ae40903d67fbc335429aa1fb956808d79ff8352a29f089f8358b38412e8f83e440df68f4eaac3d25d4f17edd5372f0f0ce8445669b6f7bc5

test:
  secret_key_base: ba294f5bd83116f650b3367443e7b40123e7167722342a936e8772b45be0910bd44b1f1a7c0deab13bf2f6633ec5d75fccc1e6987d4586bdc1e3bf7b71063ef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
